### ISSUE TITLE
Be able to load zipped version of event/geometry files

### ISSUE THREAD

**Issue by sponce** [HSF/phoenix-helpers#1]
The gain in size is typically around a factor 10, so for a web based application, it would make sense to be able to use zipped versions of our data files, both for events and geometry. Now I had a look at the code, and the thressjs GLTFLoader does not seem to support it natively, so we would have to write it ourselves

**Comment by 9inpachi** [comment]
We already do this but only in the event data import, not through the URL or anywhere else. The same logic could be extracted and reused though.

https://github.com/HSF/phoenix/blob/c6a91537c2f4bea406d6885fa562fe851bce7037/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts#L177

**Comment by sponce** [comment]
Oh nice. But when trying it, I only get "Invalid file format". How should I use it ?

**Comment by 9inpachi** [comment]
If you get that error then it means that the file does not have the .zip
extension.

**Comment by sponce** [comment]
It did. But maybe I used the wrong button. There is no button for .zip so I used the json one. Was that correct ?
There is one button for .gz though. So I've tried that one with .json.gz in the mean time and get "unexpected character at line 1 column 1 of the JSON data".

**Comment by 9inpachi** [comment]
The option is only available on ATLAS and only for event data import. Not
for geometry.

**Comment by sponce** [comment]
Ah ok. So then I should rephrase this issue into "Make zip file usage generic" maybe

**Comment by 9inpachi** [comment]
Yes, that sounds good. And have it in the main Phoenix repo? It might get lost here.

**Comment by sponce** [comment]
Yes, messed up with the repos. Closing this one, and I've opened a new one in the proper place
